### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1545]
Done:
- [x] Fixed bug in traffic.js https://github.com/dhowe/AdNauseam/issues/1583

- [x] Merge uBlock to 1.20.0

- [x] Better Implementation for private mode https://github.com/dhowe/AdNauseam/issues/1542

- [x] EFF Update https://github.com/dhowe/AdNauseam/issues/1529

- [x] Text Ads https://github.com/dhowe/AdNauseam/issues/1519

- [x] Add changes for Opera settings https://github.com/dhowe/AdNauseam/issues/1537

- [x] Translate AdNauseam code to ECMAScript 6 https://github.com/dhowe/AdNauseam/issues/1596

- [ ] Ad parsing for google ads https://github.com/dhowe/AdNauseam/issues/1556
Image, html, text ads parser created
html ad sometimes still can't be parsed due to missing href

A TODO list for next release:

- [x] Merge uBlock 1.20.0 to master branch https://github.com/dhowe/AdNauseam/tree/merge1.20.0

- [x] Crowdin Translation

- [x] Release Testing

Pinning this issue as an on-going todo list.

Post release

- [ ] Modify extension descriptions: https://github.com/dhowe/AdNauseam/issues/1579

**Comment by cqx931** [comment]
all done
