### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1620]
A TODO list:

---
https://github.com/dhowe/AdNauseam/issues/1618
https://github.com/dhowe/AdNauseam/issues/1560
---
merge to ublock 1.26.0
(not to 1.27.0 yet for a major css redesign)
Process:
- [x] 1.22
- [x] 1.23
- [x] 1.24
- [x] 1.25
- [x] 1.26
- [x] Fix messaging modernization
- [x] Fix filter lists
- [x] Fix web resources
- [x] Fix Notification
- [x] Fix badge icon
- [x] Fix Logger
- [x] Fix listsForeFilter() for the latest release merge
- [x] verify disables scriptlet injection filters (+js)
---
Before release

Test Edge version and publish to Microsoft store
https://github.com/dhowe/AdNauseam/issues/1486

**Comment by cqx931** [comment]
Edge
https://github.com/dhowe/AdNauseam/issues/1486
