### ISSUE TITLE
Release 3.9.2

### ISSUE THREAD

**Issue by cqx931** [dhowe/AdNauseam#1699]
Target: August 2020 Release

- [x] 1.27
- [x] 1.28.4
- [x] Merge to latest uBlock - 1.29

#### New features:
- [x] Strict Blocking Mode: #1681
- [x] Private Mode: #1668
- [x] ~Whitelist for ad clicking? #1697~
- [ ] Test with Brave

#### Improvements
- [x] Review CPU issue for >20k dataset #1657 
- [x] Performance improvements for storage #1711
- [x] Stats Panel #1717

#### Android
- [x] Browser.windows bug #1715
- [x] Settings page UI #1712
- [x] Menu UI #1708

---
- [ ] Upload to Edge Store

**Comment by SimonGhoul** [comment]
is site specific strick blocking mode part of the next feature? (I would use it on sites that have anything to do with Facebook or their trackers)

**Comment by dhowe** [comment]
Suggest we move this ticket into a milestone
