### ISSUE TITLE
Release Checklist v3.21.0

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2521]
### Version

 v3.21.0

### Testing

- [X] Release latest release candidate version (vX.X.XbX) on Github.
- [X] Validade the [full tests](https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates)

### Release

- [X] Release lastest version on Github
- [X] Check if https://adnauseam.io is linking to the correct latest version.

### Upload

- [X] Upload on Mozilla Firefox Extension store
- [X] Upload on Opera Extension store
- [X] Upload on Edge Extension store (only @dhowe can do that for now)

### Approval

- [x] Approved on Mozilla Firefox Extension store
- [x] Approved on Opera Extension store
- [x] Approved on Edge Extension store
