### ISSUE TITLE
Release Checklist vX.X.X

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2534]
### Version

v3.21.4

### Testing

- [X] Release latest release candidate version (vX.X.XbX) on Github.
- [X] Validade the [full tests](https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates)

### Release

- [X] Release lastest version on Github
- [ ] Check if https://adnauseam.io is linking to the correct latest version.

### Upload

- [ ] Upload on Mozilla Firefox Extension store
- [ ] Upload on Opera Extension store
- [ ] Upload on Edge Extension store (only @dhowe can do that for now)

### Approval

- [ ] Approved on Mozilla Firefox Extension store
- [ ] Approved on Opera Extension store
- [ ] Approved on Edge Extension store
