### ISSUE TITLE
Release Checklist v3.24.0

### ISSUE THREAD

**Issue by mneunomne** [dhowe/AdNauseam#2579]
### Version

v3.24.0

### Testing

- [x] Release latest release candidate version (vX.X.XbX) on Github.
- [x] Validade the [full tests](https://github.com/dhowe/AdNauseam/wiki/Testing-New-Release-Candidates)

### Release

- [x] Release lastest version on Github
- [x] Check if https://adnauseam.io is linking to the correct latest version.

### Upload

- [x] Upload on Mozilla Firefox Extension store
- [x] Upload on Opera Extension store
- [x] Upload on Edge Extension store (only @dhowe can do that for now)

### Approval

- [x] Approved on Mozilla Firefox Extension store
- [x] Approved on Opera Extension store
- [x] Approved on Edge Extension store
