### ISSUE TITLE
Check 'hpHosts Ad and tracking Servers' and 'MVPS HOSTS' lists

### ISSUE THREAD

**Issue by dhowe** [dhowe/AdNauseam#914]
We need to know, for each, if they:

**hpHosts Ad and tracking Servers**
- [ ] include cosmetic filters
- [x] block visual ads
- [ ] block other content 

**MVPS HOSTS**
- [ ] include cosmetic filters
- [x] block visual ads
- [ ] block other content

**Comment by cqx931** [comment]
What do you mean by other content?

**Comment by dhowe** [comment]
Block other things beside visual ads
